// Firebase Options Template
//
// This file is auto-generated by the FlutterFire CLI and contains
// platform-specific Firebase configuration. It should NOT be committed
// to version control as it contains sensitive API keys.
//
// SETUP INSTRUCTIONS:
// 1. Ensure you have FlutterFire CLI installed:
//    ```bash
//    dart pub global activate flutterfire_cli
//    ```
//
// 2. Run the configuration command from the comchat directory:
//    ```bash
//    cd comchat
//    flutterfire configure
//    ```
//
// 3. Follow the prompts to select your Firebase project
//    and configure for your platforms (Android, iOS, Web, etc.)
//
// 4. This will generate the actual firebase_options.dart file
//    with your Firebase credentials (which is in .gitignore)
//
// For more information, visit:
// https://firebase.google.com/docs/flutter/setup
//
// Example of the generated structure:
// ```dart
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     // Platform-specific options
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(...);
//   static const FirebaseOptions android = FirebaseOptions(...);
//   static const FirebaseOptions ios = FirebaseOptions(...);
//   // etc.
// }
// ```
